/* eslint-disable jsx-a11y/alt-text */
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica',
        fontSize: 10,
        color: '#333',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        borderBottomWidth: 3,
        borderBottomColor: '#000',
        paddingBottom: 15,
    },
    logoSection: {
        width: '40%',
    },
    logoText: {
        fontSize: 20,
        fontWeight: 'extrabold',
        color: '#000',
        textTransform: 'uppercase',
        letterSpacing: 2,
    },
    orgDetails: {
        width: '50%',
        textAlign: 'right',
        fontSize: 9,
        lineHeight: 1.4,
    },
    titleSection: {
        marginBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    docTitle: {
        fontSize: 18,
        fontWeight: 'extrabold',
        textTransform: 'uppercase',
        color: '#000',
        letterSpacing: 1,
    },
    docMeta: {
        fontSize: 10,
        textAlign: 'right',
    },
    gridTwo: {
        flexDirection: 'row',
        gap: 20,
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingBottom: 20,
    },
    col: {
        flex: 1,
    },
    sectionTitle: {
        fontSize: 9,
        color: '#64748b',
        textTransform: 'uppercase',
        fontWeight: 'bold',
        marginBottom: 5,
    },
    addressText: {
        fontSize: 10,
        lineHeight: 1.5,
    },
    bold: {
        fontWeight: 'bold',
        color: '#000',
    },
    table: {
        width: '100%',
        marginBottom: 30,
        borderWidth: 1,
        borderColor: '#94a3b8',
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#e2e8f0',
        borderBottomWidth: 1,
        borderBottomColor: '#94a3b8',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#cbd5e1',
        backgroundColor: '#fff',
    },
    th: {
        fontSize: 9,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        color: '#000',
        padding: 8,
    },
    td: {
        padding: 8,
        fontSize: 9,
        color: '#334155',
    },
    footer: {
        marginTop: 50,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        borderTopWidth: 1,
        borderTopColor: '#e2e8f0',
        paddingTop: 10,
    },
    signatureBlock: {
        textAlign: 'right',
    }
});

interface VendorInventoryDocumentProps {
    company: any;
    organization: any;
    items: any[];
}

export const VendorInventoryDocument = ({ company, organization, items }: VendorInventoryDocumentProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <View style={styles.logoSection}>
                    {organization?.logoUrl ? (
                        <Image src={organization.logoUrl} style={{ height: 50, objectFit: 'contain' }} />
                    ) : (
                        <Text style={styles.logoText}>{organization?.name}</Text>
                    )}
                </View>
                <View style={styles.orgDetails}>
                    <Text style={{ fontSize: 14, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 4 }}>
                        {organization?.name}
                    </Text>
                    {organization?.address && <Text>{organization.address}</Text>}
                    {organization?.phone && <Text>Phone: {organization.phone}</Text>}
                    {organization?.gstNumber && <Text>GSTIN: {organization.gstNumber}</Text>}
                </View>
            </View>

            {/* Title */}
            <View style={styles.titleSection}>
                <Text style={styles.docTitle}>PENDING INVENTORY REPORT</Text>
                <View style={styles.docMeta}>
                    <Text>Date: {new Date().toLocaleDateString('en-IN')}</Text>
                    <Text>Total Items: {items.length}</Text>
                </View>
            </View>

            {/* From / To Section */}
            <View style={styles.gridTwo}>
                <View style={styles.col}>
                    <Text style={styles.sectionTitle}>GENERATED BY</Text>
                    <Text style={[styles.addressText, styles.bold]}>{organization?.name}</Text>
                    <Text style={styles.addressText}>{organization?.address}</Text>
                    <Text style={styles.addressText}>Email: {organization?.email || 'N/A'}</Text>
                </View>
                <View style={styles.col}>
                    <Text style={styles.sectionTitle}>VENDOR (SERVICE CENTER)</Text>
                    <Text style={[styles.addressText, styles.bold]}>{company.name}</Text>
                    <Text style={styles.addressText}>{company.address || 'Address not available'}</Text>
                    <Text style={styles.addressText}>Phone: {company.phone || 'N/A'}</Text>
                </View>
            </View>

            {/* Notice */}
            <View style={{ marginBottom: 20 }}>
                <Text style={{ fontSize: 9, fontStyle: 'italic', color: '#666' }}>
                    NOTICE: The following items are recorded as PENDING at your facility. Please verify physical stock and update status.
                </Text>
            </View>

            {/* Table */}
            <View style={styles.table}>
                <View style={styles.tableHeader}>
                    <View style={{ width: '5%', ...styles.th }}><Text>#</Text></View>
                    <View style={{ width: '35%', ...styles.th }}><Text>Product Details</Text></View>
                    <View style={{ width: '25%', ...styles.th }}><Text>Serial Number</Text></View>
                    <View style={{ width: '15%', ...styles.th, textAlign: 'center' }}><Text>Sent Date</Text></View>
                    <View style={{ width: '10%', ...styles.th, textAlign: 'center' }}><Text>Aging</Text></View>
                    <View style={{ width: '10%', ...styles.th }}><Text>Remarks</Text></View>
                </View>
                {items.map((item, index) => {
                    // Calculate Date & Aging
                    const batchDate = item.batchDate ? new Date(item.batchDate) : new Date(item.updatedAt);
                    const diffTime = Math.abs(new Date().getTime() - batchDate.getTime());
                    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

                    return (
                        <View key={item.id} style={styles.tableRow}>
                            <View style={{ width: '5%', ...styles.td }}><Text>{index + 1}</Text></View>
                            <View style={{ width: '35%', ...styles.td }}>
                                <Text style={styles.bold}>{item.product.name}</Text>
                                <Text style={{ fontSize: 8, color: '#666' }}>{item.product.brand} {item.modelNumber ? `• ${item.modelNumber}` : ''}</Text>
                            </View>
                            <View style={{ width: '25%', ...styles.td }}><Text>{item.serialNumber}</Text></View>
                            <View style={{ width: '15%', ...styles.td, textAlign: 'center' }}>
                                <Text>{batchDate.toLocaleDateString('en-IN')}</Text>
                            </View>
                            <View style={{ width: '10%', ...styles.td, textAlign: 'center' }}>
                                <Text style={{ color: diffDays > 30 ? 'red' : 'black' }}>{diffDays} d</Text>
                            </View>
                            <View style={{ width: '10%', ...styles.td }}><Text></Text></View>
                        </View>
                    );
                })}
            </View>

            {/* Footer */}
            <View style={styles.footer}>
                <View>
                    <Text style={{ fontSize: 8, color: '#999' }}>System Generated via ReturnFlow Pro</Text>
                </View>
                <View style={styles.signatureBlock}>
                    <Text style={{ marginBottom: 30, fontSize: 9 }}>Authorized Signatory</Text>
                    <Text style={styles.bold}>{organization?.name}</Text>
                </View>
            </View>
        </Page>
    </Document>
);
